###
# Program for testing built-in functions
#
max_number = max(7,5,6,3,8,2)
print('Max number of 7,5,6,3,8,2 is', max_number)

min_number = min(4,7,2,3,9,8)
print('Min number of 4,7,2,3,9,8 is', min_number)

str_length = len("computer science")
print('The number of characters in "computer science" is', str_length)

letter = input('Enter letters: ')
print(f'The letters you entered: {letter}')

binary = bin(304)
print(f'The binary string representing decamal number 304 is {binary}')

hexa = hex(304)
print(f'The hexadecimal string representing decimal number 304 is {hexa}')

euro = ord()